angular.module('learningPortalApp')
.controller('CCDashboardCtrl', ['$scope', function($scope) {
  $scope.studentInfo = { course: 'BTech Computer Engineering', subject: 'Cloud Computing (23UGCE610)' };
  $scope.searchTerm = '';
  $scope.sortField = 'hours';

  var unit1 = { id:1, title:'Unit I: Fundamentals of Cluster, Grid and Cloud Computing', hours:10, topics:[
    { name:'Introduction to Cloud Computing', material:'Cloud computing delivers computing services over the internet including servers, storage, databases, networking, software, and analytics. It offers faster innovation, flexible resources, and economies of scale.', example:'Types: Public Cloud (AWS), Private Cloud (on-premise), Hybrid Cloud (mix of both).' },
    { name:'Benefits of Cloud Computing', material:'Key benefits include cost savings (pay-as-you-go), scalability, high availability, disaster recovery, automatic updates, and global reach.', example:'Netflix uses AWS to scale streaming to millions of users globally without owning servers.' },
    { name:'Limitations of Cloud Computing', material:'Limitations include internet dependency, data security concerns, vendor lock-in, limited control over infrastructure, and potential downtime.', example:'If AWS goes down, services like Netflix, Airbnb that depend on it also go down.' },
    { name:'Cluster Computing', material:'A cluster is a group of interconnected computers that work together as a single system. Used for high performance computing (HPC). Types: High Availability (HA) and Load Balancing clusters.', example:'Google Search uses thousands of clustered servers to handle billions of queries.' },
    { name:'Application and Classification of Cluster Computing', material:'Applications: scientific simulations, web hosting, databases. Classification: Beowulf clusters (commodity hardware), HPC clusters, HA clusters.', example:'Beowulf cluster uses Linux nodes connected via Ethernet for parallel processing.' },
    { name:'Grid Computing', material:'Grid computing connects geographically distributed computers to solve large-scale problems. Unlike clusters, grids span multiple organizations and administrative domains.', example:'SETI@home used grid computing to analyze radio signals from space using volunteer computers.' },
    { name:'Building Blocks and Applications of Grid Computing', material:'Building blocks: resource management, job scheduling, data management, security. Applications: scientific research, weather forecasting, drug discovery.', example:'CERN uses grid computing to process petabytes of data from the Large Hadron Collider.' },
    { name:'Service Models (IaaS, PaaS, SaaS)', material:'IaaS: provides virtualized computing resources (AWS EC2). PaaS: provides platform for app development (Google App Engine). SaaS: delivers software over internet (Gmail, Office 365).', example:'IaaS = renting a car, PaaS = renting a car with driver, SaaS = taking a taxi.' },
    { name:'Deployment Models', material:'Public Cloud: owned by third-party provider. Private Cloud: dedicated to one organization. Hybrid Cloud: combination. Community Cloud: shared by organizations with common goals.', example:'A hospital may use private cloud for patient data and public cloud for website.' },
    { name:'Cloud Ecosystem', material:'The cloud ecosystem includes cloud providers (AWS, Azure, GCP), cloud consumers, cloud brokers, cloud auditors, and cloud carriers. Each plays a distinct role in service delivery.', example:'AWS (provider) → Enterprise (consumer) → Accenture (broker) → Deloitte (auditor).' }
  ]};

  var unit2 = { id:2, title:'Unit II: Cloud Technologies', hours:8, topics:[
    { name:'Cloud Layers', material:'Cloud architecture has layers: Hardware layer (physical servers), Infrastructure layer (VMs, storage), Platform layer (middleware, runtime), Application layer (SaaS apps).', example:'AWS: EC2 (infrastructure) → Elastic Beanstalk (platform) → Salesforce (application).' },
    { name:'Cloud Architecture', material:'Cloud architecture consists of front-end (client devices, browsers), back-end (servers, storage, databases), cloud delivery model, and network connecting them.', example:'User browser → Internet → Load Balancer → Web Servers → Database.' },
    { name:'Hypervisors and Types', material:'A hypervisor (VMM) creates and manages virtual machines. Type 1 (bare-metal): runs directly on hardware (VMware ESXi, Hyper-V). Type 2 (hosted): runs on OS (VirtualBox, VMware Workstation).', example:'AWS uses Xen and Nitro hypervisors (Type 1) to run EC2 instances.' },
    { name:'Machine Imaging', material:'A machine image is a snapshot of a VM including OS, applications, and configurations. Used to create identical VM instances quickly. AWS calls them AMIs (Amazon Machine Images).', example:'Create an AMI of a configured web server and launch 100 identical instances in minutes.' },
    { name:'Virtualization and Types', material:'Virtualization creates virtual versions of hardware, OS, storage, or networks. Types: Full virtualization, Para-virtualization, OS-level virtualization (containers), Hardware-assisted virtualization.', example:'Docker uses OS-level virtualization (containers). VMware uses full virtualization.' },
    { name:'Load Balancer and Types', material:'Load balancers distribute incoming traffic across multiple servers. Classic Load Balancer (CLB): routes based on TCP/HTTP. Application Load Balancer (ALB): routes based on content/URL path.', example:'ALB routes /api requests to API servers and /images to image servers.' },
    { name:'Virtual Machine Technology', material:'VMs are software-based computers running on physical hardware via hypervisors. Each VM has its own OS, CPU, memory, and storage. Enables server consolidation and isolation.', example:'One physical server running 10 VMs = 10 isolated environments for different teams.' },
    { name:'Comparison of Cloud Providers', material:'AWS: largest market share, most services. Azure: strong enterprise integration with Microsoft. GCP: strong in data analytics and ML. Each differs in pricing, regions, and specialization.', example:'AWS S3 vs Azure Blob Storage vs GCP Cloud Storage — all object storage but different pricing.' }
  ]};

  var unit3 = { id:3, title:'Unit III: Management, Monitoring and MapReduce', hours:9, topics:[
    { name:'Identity Management and Access Control', material:'IAM (Identity and Access Management) controls who can access cloud resources. Involves authentication (who you are) and authorization (what you can do). Uses policies, roles, and permissions.', example:'AWS IAM: create a role that allows EC2 to read from S3 but not write.' },
    { name:'IAM Role Limitations and Benefits', material:'Benefits: fine-grained access control, no hardcoded credentials, auditable. Limitations: complex policy management, risk of over-permissioning, requires careful design.', example:'Principle of least privilege: give users only the permissions they need, nothing more.' },
    { name:'Accounts Monitoring', material:'Cloud monitoring tracks resource usage, performance, and security events. AWS CloudWatch monitors EC2, S3, RDS. Alerts can trigger auto-scaling or notifications.', example:'CloudWatch alarm: if CPU > 80% for 5 minutes, send SNS notification and scale out.' },
    { name:'User Profiles in Cloud', material:'User profiles define identity, roles, permissions, and preferences for cloud users. Managed via IAM users, groups, and roles. MFA adds extra security layer.', example:'Admin group: full access. Developer group: EC2 + S3 only. Read-only group: view only.' },
    { name:'Introduction to MapReduce', material:'MapReduce is a programming model for processing large datasets in parallel across a cluster. Two phases: Map (process and filter data) and Reduce (aggregate results).', example:'Word count: Map emits (word, 1) for each word. Reduce sums counts per word.' },
    { name:'MapReduce Programming Model', material:'Map function: takes input key-value pairs, produces intermediate key-value pairs. Reduce function: merges all intermediate values for the same key. Framework handles parallelism.', example:'Map: (doc1, "hello world") → (hello,1),(world,1). Reduce: (hello,[1,1,1]) → (hello,3).' },
    { name:'MapReduce Implementation for Cloud', material:'Cloud MapReduce runs on distributed clusters. AWS EMR (Elastic MapReduce) provides managed Hadoop/Spark clusters. Automatically handles node failures and data replication.', example:'AWS EMR processes 1TB of log data in minutes using 100 EC2 nodes with MapReduce.' },
    { name:'Introduction to Filesystem and Hadoop', material:'HDFS (Hadoop Distributed File System) stores large files across multiple nodes. Files split into blocks (128MB default), replicated 3 times for fault tolerance. NameNode manages metadata, DataNodes store data.', example:'A 1GB file is split into 8 blocks of 128MB, each replicated on 3 different DataNodes.' },
    { name:'Examples based on Hadoop and MapReduce', material:'Common Hadoop use cases: log analysis, ETL processing, recommendation systems, fraud detection. Hadoop ecosystem includes Hive (SQL), Pig (scripting), HBase (NoSQL), Spark (in-memory).', example:'Facebook uses Hadoop to process 500TB of data daily for analytics and ad targeting.' }
  ]};

  var unit4 = { id:4, title:'Unit IV: Cloud Security and Disaster Recovery', hours:9, topics:[
    { name:'Security Aspects in Cloud', material:'Cloud security covers data protection, identity management, network security, compliance, and physical security. Shared responsibility model: provider secures infrastructure, customer secures data and apps.', example:'AWS secures the data center. You secure your EC2 instances, S3 buckets, and IAM policies.' },
    { name:'Challenges and Risks in Security', material:'Key challenges: data breaches, account hijacking, insecure APIs, insider threats, shared technology vulnerabilities, data loss. Cloud introduces new attack surfaces vs traditional IT.', example:'2019 Capital One breach: misconfigured AWS WAF allowed attacker to access 100M customer records.' },
    { name:'Issues in Securing Cloud', material:'Issues include multi-tenancy risks (shared infrastructure), data residency/sovereignty, lack of visibility, compliance requirements (GDPR, HIPAA), and shadow IT.', example:'GDPR requires EU citizen data to stay in EU. Using a US-only cloud region violates this.' },
    { name:'Data Security: Methods and Tools', material:'Methods: encryption at rest (AES-256), encryption in transit (TLS), tokenization, data masking. Tools: AWS KMS (key management), CloudHSM (hardware security module), Macie (data discovery).', example:'AWS KMS encrypts S3 objects. Only users with the key can decrypt and read the data.' },
    { name:'Application Security: Methods and Tools', material:'Methods: WAF (Web Application Firewall), DDoS protection, vulnerability scanning, penetration testing. Tools: AWS Shield, AWS WAF, Inspector, Security Hub.', example:'AWS WAF blocks SQL injection and XSS attacks before they reach your web application.' },
    { name:'Disaster in Cloud', material:'Cloud disasters include: natural disasters (data center floods/fires), hardware failures, software bugs, cyberattacks, human errors, and provider outages. Multi-region deployment mitigates risk.', example:'AWS us-east-1 outage in 2021 took down Netflix, Reddit, and many other services.' },
    { name:'Recovery Plans in Cloud', material:'Recovery strategies: Backup & Restore (cheapest, slowest), Pilot Light (minimal standby), Warm Standby (scaled-down active), Multi-Site Active/Active (fastest, most expensive). RTO and RPO define recovery objectives.', example:'RTO=1hr, RPO=15min: use Warm Standby with 15-min database snapshots and quick scale-up.' }
  ]};

  var unit5 = { id:5, title:'Unit V: Edge Computing and Case Studies', hours:9, topics:[
    { name:'Introduction to Amazon Web Services', material:'AWS is the world\'s most comprehensive cloud platform with 200+ services including compute (EC2), storage (S3), databases (RDS), networking (VPC), and AI/ML (SageMaker). Launched in 2006.', example:'AWS global infrastructure: 31 regions, 99 availability zones, 400+ edge locations worldwide.' },
    { name:'AWS Different Services', material:'Compute: EC2, Lambda, ECS. Storage: S3, EBS, Glacier. Database: RDS, DynamoDB, Redshift. Networking: VPC, Route53, CloudFront. Security: IAM, KMS, Shield. Analytics: EMR, Athena, Kinesis.', example:'Startup stack: EC2 (web server) + RDS (database) + S3 (files) + CloudFront (CDN) + Route53 (DNS).' },
    { name:'Cloud Edge / Edge Computing', material:'Edge computing processes data near the source (IoT devices, sensors) rather than in a central cloud. Reduces latency, bandwidth usage, and improves real-time processing. AWS Greengrass, Azure IoT Edge.', example:'Self-driving car processes sensor data locally (edge) for instant decisions, not via cloud.' },
    { name:'Eucalyptus', material:'Eucalyptus (Elastic Utility Computing Architecture for Linking Your Programs To Useful Systems) is an open-source private cloud platform compatible with AWS APIs. Allows building AWS-compatible private clouds.', example:'A university can deploy Eucalyptus to create a private cloud for student labs, compatible with AWS tools.' },
    { name:'Windows Azure', material:'Microsoft Azure is a cloud platform with 200+ services. Strong integration with Microsoft products (Active Directory, Office 365, .NET). Azure Resource Manager (ARM) manages resources via templates.', example:'Enterprise using Office 365 + Azure AD + Azure VMs gets seamless single sign-on across all services.' },
    { name:'Pods, Silos and Aggregation', material:'Pods: isolated deployment units for scalability. Silos: isolated stacks per customer (multi-tenancy). Aggregation: combining multiple cloud services into unified solutions. Key patterns in cloud architecture.', example:'Netflix uses pod architecture where each microservice is independently deployable and scalable.' },
    { name:'Aneka', material:'Aneka is a cloud application platform by Manjrasoft for building distributed applications. Supports multiple programming models: Thread, Task, MapReduce. Provides SLA-based resource management.', example:'Aneka can run a scientific simulation by distributing tasks across cloud VMs with guaranteed SLAs.' },
    { name:'Google App Engine', material:'Google App Engine (GAE) is a PaaS for building and hosting web apps. Supports Python, Java, Go, PHP. Auto-scales based on traffic. No server management required. Part of Google Cloud Platform.', example:'A startup deploys a Python Flask app on GAE — it auto-scales from 10 to 10,000 users with zero config.' }
  ]};

  $scope.syllabus = [unit1, unit2, unit3, unit4, unit5];
}]);
