angular.module('learningPortalApp')
.controller('DMDashboardCtrl', ['$scope', '$location', function($scope, $location) {
  var user = JSON.parse(localStorage.getItem('ulp_session') || 'null');
  if (!user) { $location.path('/login'); return; }
  if (user.role === 'admin') { $location.path('/admin'); return; }
  if (user.role === 'faculty') { $location.path('/faculty'); return; }

  $scope.studentInfo = { course: 'BTech Computer Engineering', subject: 'Data Mining & Data Warehousing (23UGCE602)' };
  $scope.searchTerm = '';
  $scope.sortField = 'hours';

  var unit1 = { id:1, title:'Unit I: Fundamentals of Data Mining & Data Warehousing', hours:9, topics:[
    { name:'Importance and Applications of DM & DW', material:'Data Mining extracts hidden patterns from large datasets. Data Warehousing stores integrated historical data for analysis. Applications: retail (customer behavior), healthcare (disease prediction), finance (fraud detection), marketing (targeted ads).', example:'Amazon uses DM to recommend products. Walmart uses DW to analyze sales across 11,000 stores.' },
    { name:'Major Issues in Mining and Warehousing', material:'Issues in DM: noisy/incomplete data, scalability, high dimensionality, privacy. Issues in DW: data integration from multiple sources, ETL complexity, storage cost, query performance.', example:'A bank mining credit card fraud must handle millions of transactions with <1% fraud rate (imbalanced data).' },
    { name:'Structured and Unstructured Data', material:'Structured: organized in rows/columns (SQL databases, spreadsheets). Unstructured: no predefined format (emails, social media, images, videos). Semi-structured: JSON, XML. 80% of enterprise data is unstructured.', example:'Structured: employee table. Unstructured: customer reviews on Amazon. Semi-structured: JSON API response.' },
    { name:'OLAP vs OLTP', material:'OLTP (Online Transaction Processing): handles day-to-day transactions, normalized DB, fast inserts/updates, many users. OLAP (Online Analytical Processing): handles complex queries for analysis, denormalized, read-heavy, few users.', example:'OLTP: ATM transaction. OLAP: "What were total sales by region for last 5 years?" query on DW.' },
    { name:'OLAP Operations', material:'Slice: select one dimension value (sales for 2023 only). Dice: select range of values across dimensions. Roll-up: aggregate data (daily → monthly → yearly). Drill-down: go from summary to detail (yearly → monthly → daily).', example:'Sales cube: Slice by Year=2023. Dice by Region=North AND Product=Electronics. Roll-up: city→state→country.' },
    { name:'Data Warehouse Schemas', material:'Star Schema: central fact table surrounded by dimension tables (simple, fast queries). Snowflake Schema: normalized dimension tables (saves space, complex joins). Fact Constellation: multiple fact tables sharing dimension tables.', example:'Star: Sales_Fact → Date_Dim, Product_Dim, Store_Dim. Snowflake: Product_Dim → Category_Dim → Department_Dim.' },
    { name:'Applications: Business Analytics and Financial Reporting', material:'Business Analytics: sales forecasting, customer segmentation, supply chain optimization. Financial Reporting: profit/loss analysis, budget variance, regulatory compliance reports using DW as single source of truth.', example:'Tableau + Snowflake DW: CFO gets real-time P&L dashboard pulling from 20+ source systems via ETL.' }
  ]};

  var unit2 = { id:2, title:'Unit II: Architecture and Processes of DM & DW', hours:9, topics:[
    { name:'Three-tier Architecture of Data Warehousing', material:'Tier 1: Bottom tier — Data sources (OLTP DBs, flat files, external data) + ETL layer. Tier 2: Middle tier — Data Warehouse server (OLAP engine, data marts). Tier 3: Top tier — Front-end tools (reports, dashboards, mining tools).', example:'Tier1: MySQL + Oracle DBs → ETL (Informatica) → Tier2: Redshift DW → Tier3: Tableau dashboards.' },
    { name:'Architecture of Data Mining Systems', material:'Components: Data sources → Data warehouse → DM engine (algorithms) → Pattern evaluation → Knowledge base → User interface. DM engine applies algorithms (classification, clustering, association) on preprocessed data.', example:'Netflix DM system: viewing history DB → preprocessing → collaborative filtering engine → recommendations UI.' },
    { name:'ETL Process', material:'Extract: pull data from multiple heterogeneous sources. Transform: clean, validate, convert formats, apply business rules. Load: insert into data warehouse. ETL runs on schedule (nightly batch) or real-time (streaming ETL).', example:'Extract: sales from Oracle + web logs from S3. Transform: standardize date formats, remove duplicates. Load: into Redshift.' },
    { name:'Classification of DM Systems', material:'By DB type: relational, transactional, object-relational, spatial. By knowledge type: characterization, discrimination, association, classification, clustering, outlier analysis. By technique: statistical, ML, neural networks, visualization.', example:'Spatial DM: Google Maps mining GPS data to predict traffic. Text DM: Gmail spam filter classifying emails.' },
    { name:'DM Task Primitives', material:'Task primitives specify a DM task: data set to mine, kind of knowledge to discover, background knowledge, interestingness measures, representation of discovered patterns. Used to define mining queries.', example:'Mine: sales_db. Find: association rules. With support > 2%, confidence > 50%. Display as: rule table.' },
    { name:'KDD Process', material:'KDD (Knowledge Discovery in Databases): Selection → Preprocessing → Transformation → Data Mining → Interpretation/Evaluation. Data Mining is just one step in the broader KDD process.', example:'KDD for churn prediction: select customer data → clean missing values → normalize → apply decision tree → evaluate accuracy.' },
    { name:'Applications: Enterprise Data Management', material:'Enterprise DW consolidates data from ERP, CRM, SCM systems. Cloud-based warehousing (Snowflake, BigQuery, Redshift) offers scalability, pay-per-query pricing, and no infrastructure management.', example:'Snowflake DW: auto-scales compute for Black Friday traffic spike, scales down after — pay only for what you use.' }
  ]};

  var unit3 = { id:3, title:'Unit III: Data Preprocessing for Quality Improvement', hours:10, topics:[
    { name:'Need for Data Preprocessing', material:'"Garbage in, garbage out." Real-world data is dirty: incomplete (missing values), noisy (errors), inconsistent (conflicting data), redundant (duplicate records). Preprocessing improves data quality and mining accuracy.', example:'Hospital dataset: age=-5 (error), income=null (missing), same patient with two different IDs (inconsistent).' },
    { name:'Data Cleaning: Missing Values', material:'Methods: ignore the tuple, fill manually, use global constant ("unknown"), use attribute mean/median, use most probable value (regression/Bayesian). Choice depends on data type and missing percentage.', example:'Age column: 5% missing → fill with median age. Income: 30% missing → use regression to predict from education+job.' },
    { name:'Data Cleaning: Outliers and Noisy Data', material:'Outliers: values far from normal distribution. Detection: box plots, Z-score, IQR method. Noisy data: random errors. Handling: binning (smoothing), regression, clustering-based outlier detection.', example:'Salary dataset: most values 30K-100K, one value 10M → outlier. Z-score > 3 → flag as outlier for review.' },
    { name:'Data Summarization and Integration', material:'Summarization: descriptive stats (mean, median, mode, variance, range). Integration: combining data from multiple sources. Issues: entity identification (same entity different names), redundancy (correlated attributes), data value conflicts.', example:'Merging customer DB from two companies: "John Smith" vs "J. Smith" — same person? Use record linkage techniques.' },
    { name:'Data Transformation and Reduction', material:'Transformation: normalization (min-max, z-score), aggregation, generalization. Reduction: dimensionality reduction (PCA), numerosity reduction (sampling, histograms), data compression. Goal: smaller dataset, same analytical results.', example:'Min-max normalization: salary 20K-100K → 0 to 1 scale. PCA: reduce 100 features to 10 principal components.' },
    { name:'Data Discretization and Hierarchy', material:'Discretization: convert continuous to discrete (age → young/middle/old). Methods: equal-width binning, equal-frequency binning, entropy-based. Concept hierarchy: generalizes data (city → state → country → continent).', example:'Age: 0-18=child, 19-35=young, 36-55=middle, 56+=senior. City hierarchy: Surat→Gujarat→India→Asia.' }
  ]};

  var unit4 = { id:4, title:'Unit IV: Association Rule Mining & Pattern Interpretation', hours:8, topics:[
    { name:'Concept Descriptions and Attribute Relevance', material:'Concept description: characterization (summarize target class) and discrimination (compare target vs contrast class). Attribute relevance: identify which attributes are most useful for mining using information gain, chi-square test.', example:'Characterize "high-value customers": age 25-45, income >50K, frequent buyer. Discriminate from low-value customers.' },
    { name:'Association Rule Mining', material:'Association rules: IF antecedent THEN consequent. Example: {bread, butter} → {milk}. Support: frequency of itemset. Confidence: P(consequent|antecedent). Lift: how much better than random. Rules with high support + confidence are interesting.', example:'{diapers} → {beer}: support=2%, confidence=60%, lift=2.5. Supermarkets place beer near diapers based on this rule.' },
    { name:'Frequent Itemset Generation', material:'Frequent itemset: set of items with support ≥ min_support threshold. Key property: Apriori principle — all subsets of a frequent itemset must also be frequent. Used to prune search space.', example:'Transactions: {A,B,C},{A,B},{B,C},{A,C},{A,B,C}. Min_support=60%: {A}=80%, {B}=80%, {C}=80%, {A,B}=60% are frequent.' },
    { name:'Apriori Algorithm', material:'Step 1: Find frequent 1-itemsets (L1). Step 2: Generate candidate 2-itemsets (C2) from L1. Step 3: Prune candidates with infrequent subsets. Step 4: Scan DB to find frequent 2-itemsets (L2). Repeat until no new frequent itemsets.', example:'L1={A,B,C,D}. C2={AB,AC,AD,BC,BD,CD}. After scan: L2={AB,AC,BC}. C3={ABC}. After scan: L3={ABC} if support≥min.' },
    { name:'Evaluation and Validation of Association Rules', material:'Metrics: Support (frequency), Confidence (reliability), Lift (>1 means positive correlation), Conviction, Leverage. Avoid spurious rules: use statistical significance tests. Cross-validation on held-out data.', example:'Rule: {coffee}→{sugar}: support=30%, confidence=70%, lift=1.4 (positive association). Lift<1 means negative association.' },
    { name:'Market Basket Analysis', material:'Classic application of association rule mining. Analyzes customer purchase patterns to find items bought together. Used for: product placement, cross-selling, promotions, inventory management.', example:'Walmart MBA finding: customers buying storm supplies also buy Pop-Tarts. Stock Pop-Tarts near emergency supplies.' }
  ]};

  var unit5 = { id:5, title:'Unit V: Classification & Clustering Techniques', hours:9, topics:[
    { name:'Overview of Classification and Clustering', material:'Classification: supervised learning — predict class label for new data using labeled training data. Clustering: unsupervised learning — group similar data points without predefined labels. Classification answers "what class?" Clustering answers "what groups exist?"', example:'Classification: email → spam/not-spam (labeled training data). Clustering: group customers by behavior (no labels).' },
    { name:'Issues in Classification', material:'Overfitting: model too complex, memorizes training data, poor on new data. Underfitting: model too simple. Class imbalance: rare class (fraud) hard to detect. Missing values, irrelevant features, high dimensionality.', example:'Decision tree with depth=20 overfits. Pruning reduces depth to 5 → better generalization on test data.' },
    { name:'Decision Trees', material:'Tree structure: internal nodes = attribute tests, branches = outcomes, leaves = class labels. Algorithm: ID3 (information gain), C4.5 (gain ratio), CART (Gini index). Advantages: interpretable, handles mixed data types.', example:'Play tennis? Root: Outlook. Sunny→Humidity: High=No, Normal=Yes. Overcast=Yes. Rainy→Wind: Strong=No, Weak=Yes.' },
    { name:'Naïve Bayes and Bayes Theorem', material:'Bayes Theorem: P(C|X) = P(X|C)×P(C)/P(X). Naïve Bayes assumes feature independence. Despite "naïve" assumption, works well for text classification, spam filtering. Fast, simple, handles high dimensions well.', example:'Spam filter: P(spam|"free","money","win") = P("free"|spam)×P("money"|spam)×P("win"|spam)×P(spam)/P(X).' },
    { name:'K-Means and K-Medoids Clustering', material:'K-Means: assign points to nearest centroid, update centroids, repeat until convergence. K-Medoids (PAM): uses actual data points as cluster centers (more robust to outliers). Both require specifying K.', example:'K-Means with K=3: randomly place 3 centroids, assign each customer to nearest, recalculate centroids, repeat 10 iterations.' },
    { name:'Hierarchical Clustering', material:'Agglomerative (bottom-up): start with each point as cluster, merge closest pairs. Divisive (top-down): start with one cluster, split. Result: dendrogram. No need to specify K. Linkage: single, complete, average.', example:'Dendrogram of 5 customers: cut at height 3 → 2 clusters. Cut at height 1 → 4 clusters. Choose cut based on domain.' },
    { name:'Support Vector Machines (SVM)', material:'SVM finds optimal hyperplane maximizing margin between classes. Support vectors: data points closest to hyperplane. Linear SVM: linearly separable data. Non-linear SVM: kernel trick (RBF, polynomial) maps to higher dimension.', example:'Linear SVM: separate cats vs dogs with a line. Non-linear SVM with RBF kernel: separate concentric circles of data.' }
  ]};

  $scope.syllabus = [unit1, unit2, unit3, unit4, unit5];
}]);
