angular.module('learningPortalApp')
.controller('DMLabCtrl', ['$scope', '$location', 'FirebaseService', function($scope, $location, FirebaseService) {

  var user = JSON.parse(localStorage.getItem('ulp_session') || 'null');
  if (!user) { $location.path('/login'); return; }
  if (user.role === 'admin') { $location.path('/admin'); return; }
  if (user.role === 'faculty') { $location.path('/faculty'); return; }

  var SUBJECT_ID   = 'dm-dw';
  var PROGRESS_KEY = 'ulp_progress_' + SUBJECT_ID;

  var defaultPracticals = [
    { title:'Compare DM & DW Tools', aim:'Identify and compare features of popular Data Mining and Data Warehousing tools.', code:'// DM Tools: WEKA, RapidMiner, Orange, scikit-learn, R (caret)\n// DW Tools: Amazon Redshift, Google BigQuery, Snowflake, Azure Synapse, Apache Hive\n// WEKA: open source, Java, GUI, algorithms: J48, NaiveBayes, K-Means\n// RapidMiner: drag-drop workflow, 1500+ operators\n// Redshift: cloud DW, columnar storage, petabyte scale\n// BigQuery: serverless, pay-per-query, ML built-in\n// Snowflake: multi-cloud, auto-scaling, data sharing' },
    { title:'Data Cube - Snowflake Schema (Airport)', aim:'Design and create a data cube using a snowflake schema for an Airport Authority dataset.', code:'-- Snowflake Schema\nCREATE TABLE Flight_Fact (flight_id INT, date_id INT, airport_id INT, airline_id INT, passengers INT, revenue DECIMAL(10,2));\nCREATE TABLE Date_Dim (date_id INT, date DATE, month_id INT);\nCREATE TABLE Month_Dim (month_id INT, month_name VARCHAR(20), quarter INT, year INT);\nCREATE TABLE Airport_Dim (airport_id INT, airport_code VARCHAR(5), city_id INT);\nCREATE TABLE City_Dim (city_id INT, city_name VARCHAR(50), state VARCHAR(50));\n-- Query: Revenue by airline and quarter\nSELECT a.airline_name, m.quarter, SUM(f.revenue) as total_revenue\nFROM Flight_Fact f JOIN Airline_Dim a ON f.airline_id=a.airline_id\nJOIN Date_Dim d ON f.date_id=d.date_id JOIN Month_Dim m ON d.month_id=m.month_id\nGROUP BY a.airline_name, m.quarter;' },
    { title:'Data Cube - Fact Constellation (Cricket)', aim:'Design and create a data cube using a Fact constellation schema for a Cricket Team dataset.', code:'-- Fact Constellation: two fact tables sharing dimensions\nCREATE TABLE Player_Dim (player_id INT, player_name VARCHAR(100), country VARCHAR(50));\nCREATE TABLE Match_Dim (match_id INT, match_date DATE, venue VARCHAR(100), match_type VARCHAR(20));\nCREATE TABLE Batting_Fact (player_id INT, match_id INT, runs_scored INT, balls_faced INT, strike_rate DECIMAL(5,2));\nCREATE TABLE Bowling_Fact (player_id INT, match_id INT, wickets INT, runs_given INT, economy DECIMAL(4,2));\n-- Top scorers by match type\nSELECT p.player_name, m.match_type, SUM(b.runs_scored) as total_runs\nFROM Batting_Fact b JOIN Player_Dim p ON b.player_id=p.player_id\nJOIN Match_Dim m ON b.match_id=m.match_id\nGROUP BY p.player_name, m.match_type ORDER BY total_runs DESC LIMIT 10;' },
    { title:'OLAP Operations - Courier Company', aim:'Perform OLAP operations: slice, dice, roll-up, drill-down on a courier company cube.', code:'CREATE TABLE Courier_Fact (date DATE, region VARCHAR(50), service_type VARCHAR(30), deliveries INT, revenue DECIMAL(10,2));\n-- SLICE: Fix one dimension\nSELECT date, region, deliveries FROM Courier_Fact WHERE service_type = "Express";\n-- DICE: Multiple dimension ranges\nSELECT * FROM Courier_Fact WHERE region IN ("North","South") AND date BETWEEN "2024-01-01" AND "2024-03-31";\n-- ROLL-UP: Daily to Yearly\nSELECT YEAR(date) as year, SUM(deliveries) as total FROM Courier_Fact GROUP BY YEAR(date);\n-- DRILL-DOWN: Year to Month\nSELECT YEAR(date) yr, MONTH(date) mo, SUM(revenue) rev FROM Courier_Fact WHERE YEAR(date)=2024 GROUP BY yr, mo;' },
    { title:'Attribute Relevance - Weather Data', aim:'Analyze attribute relevance using a weather data warehouse.', code:'# Attribute Relevance using Mutual Information\nimport pandas as pd\nfrom sklearn.feature_selection import mutual_info_classif\nfrom sklearn.preprocessing import LabelEncoder\ndata = {"outlook":["sunny","sunny","overcast","rainy","rainy","rainy","overcast","sunny","sunny","rainy","sunny","overcast","overcast","rainy"],\n  "temperature":["hot","hot","hot","mild","cool","cool","cool","mild","cool","mild","mild","mild","hot","mild"],\n  "humidity":["high","high","high","high","normal","normal","normal","high","normal","normal","normal","high","normal","high"],\n  "wind":["weak","strong","weak","weak","weak","strong","strong","weak","weak","weak","strong","strong","weak","strong"],\n  "play":["no","no","yes","yes","yes","no","yes","no","yes","yes","yes","yes","yes","no"]}\ndf = pd.DataFrame(data)\nle = LabelEncoder()\nfor col in df.columns: df[col] = le.fit_transform(df[col])\nX = df.drop("play",axis=1); y = df["play"]\nscores = mutual_info_classif(X, y, random_state=42)\nfor f, s in zip(X.columns, scores): print(f"{f}: {s:.4f}")' },
    { title:'Hadoop Framework for Distributed Processing', aim:'Demonstrate the use of Hadoop Framework for distributed data processing.', code:'# mapper.py\nimport sys\nfor line in sys.stdin:\n    for word in line.strip().split():\n        print(f"{word}\\t1")\n\n# reducer.py\nimport sys\nfrom collections import defaultdict\nwc = defaultdict(int)\nfor line in sys.stdin:\n    w, c = line.strip().split("\\t")\n    wc[w] += int(c)\nfor w, c in sorted(wc.items()): print(f"{w}\\t{c}")\n\n# Run:\n# hadoop jar hadoop-streaming.jar -input /input/data.txt -output /output/wc -mapper mapper.py -reducer reducer.py' },
    { title:'Social Media Data Mining', aim:'Explore and analyze patterns from social media data.', code:'import pandas as pd, re\nfrom collections import Counter\nposts = [\n  {"text":"Love iPhone! #Apple #Tech","likes":150},\n  {"text":"Python for data science #Python #ML","likes":200},\n  {"text":"Cloud is future #AWS #Cloud #Tech","likes":180},\n  {"text":"Data mining finds patterns #DataMining #ML","likes":220}\n]\ndf = pd.DataFrame(posts)\nall_tags = [t for text in df.text for t in re.findall(r"#\\w+", text)]\nprint("Top Hashtags:", Counter(all_tags).most_common(5))\nprint("Avg Likes:", df.likes.mean())' },
    { title:'Naïve Bayes Classification', aim:'Implement Naïve Bayes algorithm to generate classification rules.', code:'from sklearn.naive_bayes import CategoricalNB\nfrom sklearn.preprocessing import LabelEncoder\nimport numpy as np\nX_raw = [["sunny","hot","high","weak"],["sunny","hot","high","strong"],["overcast","hot","high","weak"],\n  ["rainy","mild","high","weak"],["rainy","cool","normal","weak"],["rainy","cool","normal","strong"],\n  ["overcast","cool","normal","strong"],["sunny","mild","high","weak"],["sunny","cool","normal","weak"],\n  ["rainy","mild","normal","weak"],["sunny","mild","normal","strong"],["overcast","mild","high","strong"],\n  ["overcast","hot","normal","weak"],["rainy","mild","high","strong"]]\ny_raw = ["no","no","yes","yes","yes","no","yes","no","yes","yes","yes","yes","yes","no"]\nles = [LabelEncoder() for _ in range(4)]\nX = np.array([[les[i].fit_transform([r[i] for r in X_raw])[j] for i in range(4)] for j in range(len(X_raw))])\ny = LabelEncoder().fit_transform(y_raw)\nmodel = CategoricalNB(); model.fit(X, y)\nprint("Accuracy:", (model.predict(X)==y).mean())' },
    { title:'Data Preprocessing Techniques', aim:'Apply preprocessing: handling missing values, sampling, and binning.', code:'import pandas as pd, numpy as np\nfrom sklearn.preprocessing import MinMaxScaler\nnp.random.seed(42)\ndf = pd.DataFrame({"age":[25,np.nan,35,45,np.nan,28,52,33,np.nan,41],\n  "income":[30000,45000,np.nan,80000,25000,np.nan,95000,42000,38000,70000]})\nprint("Missing:\\n", df.isnull().sum())\ndf["age"].fillna(df["age"].median(), inplace=True)\ndf["income"].fillna(df["income"].mean(), inplace=True)\ndf["age_group"] = pd.cut(df["age"], bins=[0,30,40,60], labels=["Young","Middle","Senior"])\ndf["income_norm"] = MinMaxScaler().fit_transform(df[["income"]])\nprint(df)' },
    { title:'Apriori Algorithm', aim:'Implement the Apriori algorithm to discover frequent itemsets and generate association rules.', code:'# pip install mlxtend\nfrom mlxtend.frequent_patterns import apriori, association_rules\nfrom mlxtend.preprocessing import TransactionEncoder\nimport pandas as pd\ntransactions = [\n  ["bread","milk","butter"],["bread","diapers","beer","eggs"],\n  ["milk","diapers","beer","cola"],["bread","milk","diapers","beer"],\n  ["bread","milk","diapers","cola"],["milk","butter"],\n  ["bread","butter","eggs"],["bread","milk","diapers"]\n]\nte = TransactionEncoder()\ndf = pd.DataFrame(te.fit_transform(transactions), columns=te.columns_)\nfreq = apriori(df, min_support=0.375, use_colnames=True)\nrules = association_rules(freq, metric="confidence", min_threshold=0.6)\nprint(rules[["antecedents","consequents","support","confidence","lift"]])' },
    { title:'K-Means and K-Medoids Clustering', aim:'Perform clustering using K-Means and K-Medoids.', code:'from sklearn.cluster import KMeans\nfrom sklearn.datasets import make_blobs\nX, _ = make_blobs(n_samples=150, centers=3, cluster_std=0.8, random_state=42)\nkm = KMeans(n_clusters=3, random_state=42, n_init=10)\nkm.fit(X)\nprint("K-Means Inertia:", km.inertia_)\nprint("Centers:\\n", km.cluster_centers_)\n# K-Medoids (pip install scikit-learn-extra)\nfrom sklearn_extra.cluster import KMedoids\nkmed = KMedoids(n_clusters=3, random_state=42)\nkmed.fit(X)\nprint("K-Medoids Centers:\\n", kmed.cluster_centers_)' },
    { title:'Regression using WEKA', aim:'Evaluate regression techniques using WEKA.', code:'// WEKA Steps:\n// 1. Open WEKA Explorer → Preprocess → Open housing.arff\n// 2. Classify → Choose → functions → LinearRegression\n// 3. Test: Cross-validation, 10 folds → Start\n// 4. Read: Correlation coefficient, MAE, RMSE\n// ARFF Format:\n// @relation housing\n// @attribute size NUMERIC\n// @attribute bedrooms NUMERIC\n// @attribute price NUMERIC\n// @data\n// 1500, 3, 250000\n// 2000, 4, 350000\n// Compare: SMOreg, M5P, MultilayerPerceptron' },
    { title:'Binning and Histogram Analysis', aim:'Implement binning and histogram analysis.', code:'import pandas as pd, numpy as np, matplotlib.pyplot as plt\nnp.random.seed(42)\nages = np.clip(np.random.normal(35,12,200).astype(int), 18, 70)\ndf = pd.DataFrame({"age": ages})\n# Equal-width binning\ndf["ew_bin"] = pd.cut(df["age"], bins=5)\nprint("Equal-Width:\\n", df["ew_bin"].value_counts().sort_index())\n# Equal-frequency binning\ndf["ef_bin"] = pd.qcut(df["age"], q=5, duplicates="drop")\nprint("Equal-Freq:\\n", df["ef_bin"].value_counts().sort_index())\nplt.hist(ages, bins=10, color="steelblue", edgecolor="black")\nplt.title("Age Distribution"); plt.savefig("histogram.png")' },
    { title:'Classification Process on Given Data', aim:'Demonstrate classification process on given data.', code:'from sklearn.datasets import load_iris\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.tree import DecisionTreeClassifier, export_text\nfrom sklearn.metrics import accuracy_score, classification_report\niris = load_iris()\nX_train, X_test, y_train, y_test = train_test_split(iris.data, iris.target, test_size=0.3, random_state=42, stratify=iris.target)\ndt = DecisionTreeClassifier(max_depth=3, random_state=42)\ndt.fit(X_train, y_train)\ny_pred = dt.predict(X_test)\nprint("Accuracy:", accuracy_score(y_test, y_pred))\nprint(classification_report(y_test, y_pred, target_names=iris.target_names))' },
    { title:'Compare Classifiers using Confusion Matrix', aim:'Compare classification algorithm accuracies using a confusion matrix.', code:'from sklearn.datasets import load_breast_cancer\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.naive_bayes import GaussianNB\nfrom sklearn.svm import SVC\nfrom sklearn.neighbors import KNeighborsClassifier\nfrom sklearn.metrics import accuracy_score, confusion_matrix\ndata = load_breast_cancer()\nX_tr, X_te, y_tr, y_te = train_test_split(data.data, data.target, test_size=0.3, random_state=42)\nclfs = {"Decision Tree":DecisionTreeClassifier(random_state=42),"Naive Bayes":GaussianNB(),"SVM":SVC(random_state=42),"KNN":KNeighborsClassifier()}\nfor name, clf in clfs.items():\n  clf.fit(X_tr, y_tr); pred = clf.predict(X_te)\n  print(f"{name}: {accuracy_score(y_te,pred):.4f}")' }
  ];

  function loadProgress() {
    try { return JSON.parse(localStorage.getItem(PROGRESS_KEY)) || {}; } catch(e) { return {}; }
  }
  function saveProgress() {
    var data = {};
    $scope.practicals.forEach(function(p) { data[p.id] = { completed: p.completed, notes: p.notes }; });
    localStorage.setItem(PROGRESS_KEY, JSON.stringify(data));
  }
  function buildList(source) {
    var progress = loadProgress();
    $scope.practicals = source.map(function(p, i) {
      var id = i + 1, s = progress[id] || {};
      return { id:id, title:p.title, aim:p.aim, code:p.code,
               completed: s.completed||false, notes: s.notes||'', showCode:false };
    });
  }

  FirebaseService.getPracticals(SUBJECT_ID).then(function(list) {
    buildList(list && list.length ? list : defaultPracticals);
  });

  $scope.toggleComplete = function(p) { p.completed = !p.completed; saveProgress(); };
  $scope.toggleCode     = function(p) { p.showCode = !p.showCode; };
  $scope.saveNotes      = function()  { saveProgress(); };
  $scope.completedCount = function()  { return $scope.practicals.filter(function(p){return p.completed;}).length; };
}]);
