angular.module('learningPortalApp')
.controller('DMLabCtrl', ['$scope', function($scope) {
  var STORAGE_KEY = 'ulp_dm_practicals';
  function loadSaved() { try { return JSON.parse(localStorage.getItem(STORAGE_KEY)) || {}; } catch(e) { return {}; } }
  function save() { var d={}; $scope.practicals.forEach(function(p){ d[p.id]={completed:p.completed,notes:p.notes}; }); localStorage.setItem(STORAGE_KEY,JSON.stringify(d)); }

  var practicalData = [
    { title:'Compare DM & DW Tools', aim:'Identify and compare features of popular Data Mining and Data Warehousing tools.', code:'// DM Tools: WEKA, RapidMiner, Orange, Python scikit-learn\n// DW Tools: Amazon Redshift, Google BigQuery, Snowflake\n// WEKA: open source, Java, GUI, J48/NaiveBayes/K-Means\n// RapidMiner: drag-drop, 1500+ operators\n// Redshift: columnar, petabyte scale\n// BigQuery: serverless, pay-per-query' },
    { title:'Data Cube - Snowflake Schema (Airport)', aim:'Design a data cube using snowflake schema for Airport Authority.', code:'-- Snowflake Schema\nCREATE TABLE Flight_Fact(flight_id INT, date_id INT, airline_id INT, passengers INT, revenue DECIMAL(10,2));\nCREATE TABLE Date_Dim(date_id INT, date DATE, month_id INT);\nCREATE TABLE Month_Dim(month_id INT, month_name VARCHAR(20), quarter INT, year INT);\nCREATE TABLE Airline_Dim(airline_id INT, airline_name VARCHAR(100));\n-- Query\nSELECT a.airline_name, m.quarter, SUM(f.revenue) total\nFROM Flight_Fact f JOIN Airline_Dim a ON f.airline_id=a.airline_id\nJOIN Date_Dim d ON f.date_id=d.date_id JOIN Month_Dim m ON d.month_id=m.month_id\nGROUP BY a.airline_name, m.quarter;' },
    { title:'Data Cube - Fact Constellation (Cricket)', aim:'Design a data cube using Fact Constellation schema for Cricket Team.', code:'-- Two fact tables sharing dimensions\nCREATE TABLE Player_Dim(player_id INT, player_name VARCHAR(100), country VARCHAR(50));\nCREATE TABLE Match_Dim(match_id INT, match_date DATE, match_type VARCHAR(20));\nCREATE TABLE Batting_Fact(player_id INT, match_id INT, runs_scored INT, strike_rate DECIMAL(5,2));\nCREATE TABLE Bowling_Fact(player_id INT, match_id INT, wickets INT, economy DECIMAL(4,2));\n-- Top scorers\nSELECT p.player_name, m.match_type, SUM(b.runs_scored) total_runs\nFROM Batting_Fact b JOIN Player_Dim p ON b.player_id=p.player_id\nJOIN Match_Dim m ON b.match_id=m.match_id\nGROUP BY p.player_name, m.match_type ORDER BY total_runs DESC;' },
    { title:'OLAP Operations - Courier Company', aim:'Perform OLAP: slice, dice, roll-up, drill-down on courier company cube.', code:'-- SLICE: one dimension fixed\nSELECT date, region, deliveries FROM Courier_Fact WHERE service_type="Express";\n-- DICE: multiple dimension ranges\nSELECT * FROM Courier_Fact WHERE region IN("North","South") AND date BETWEEN "2024-01-01" AND "2024-03-31";\n-- ROLL-UP: daily to yearly\nSELECT YEAR(date) yr, SUM(deliveries) total FROM Courier_Fact GROUP BY yr;\n-- DRILL-DOWN: year to month\nSELECT YEAR(date) yr, MONTH(date) mo, SUM(revenue) rev FROM Courier_Fact WHERE YEAR(date)=2024 GROUP BY yr,mo;' },
    { title:'Attribute Relevance - Weather Data', aim:'Analyze attribute relevance using weather data warehouse.', code:'import pandas as pd\nfrom sklearn.feature_selection import mutual_info_classif\nfrom sklearn.preprocessing import LabelEncoder\nimport numpy as np\ndata={"outlook":["sunny","sunny","overcast","rainy","rainy","rainy","overcast","sunny","sunny","rainy","sunny","overcast","overcast","rainy"],"temperature":["hot","hot","hot","mild","cool","cool","cool","mild","cool","mild","mild","mild","hot","mild"],"humidity":["high","high","high","high","normal","normal","normal","high","normal","normal","normal","high","normal","high"],"wind":["weak","strong","weak","weak","weak","strong","strong","weak","weak","weak","strong","strong","weak","strong"],"play":["no","no","yes","yes","yes","no","yes","no","yes","yes","yes","yes","yes","no"]}\ndf=pd.DataFrame(data)\nle=LabelEncoder()\nfor c in df.columns: df[c]=le.fit_transform(df[c])\nX=df.drop("play",axis=1); y=df["play"]\nscores=mutual_info_classif(X,y,random_state=42)\nfor f,s in zip(X.columns,scores): print(f"{f}: {s:.4f}")' },
    { title:'Hadoop MapReduce', aim:'Demonstrate Hadoop Framework for distributed data processing.', code:'# mapper.py\nimport sys\nfor line in sys.stdin:\n    for word in line.strip().split():\n        print(f"{word}\t1")\n\n# reducer.py\nimport sys\nfrom collections import defaultdict\nwc=defaultdict(int)\nfor line in sys.stdin:\n    w,c=line.strip().split("\t"); wc[w]+=int(c)\nfor w,c in sorted(wc.items()): print(f"{w}\t{c}")\n\n# Run:\n# hadoop jar hadoop-streaming.jar -input /input/data.txt -output /output/wc -mapper mapper.py -reducer reducer.py' },
    { title:'Social Media Data Mining', aim:'Explore and analyze patterns from social media data.', code:'import pandas as pd, re\nfrom collections import Counter\nposts=[{"text":"Love iPhone! #Apple #Tech","likes":150},{"text":"Python for DS #Python #ML","likes":200},{"text":"Cloud future #AWS #Cloud","likes":180},{"text":"DM finds patterns #DataMining #ML","likes":220}]\ndf=pd.DataFrame(posts)\ntags=[t for text in df.text for t in re.findall(r"#\w+",text)]\nprint("Top Tags:",Counter(tags).most_common(5))\nprint("Avg Likes:",df.likes.mean())\nprint("Most Liked:",df.loc[df.likes.idxmax(),"text"])' },
    { title:'Naive Bayes Classification', aim:'Implement Naive Bayes algorithm to generate classification rules.', code:'from sklearn.naive_bayes import CategoricalNB\nfrom sklearn.preprocessing import LabelEncoder\nimport numpy as np\nX_raw=[["sunny","hot","high","weak"],["sunny","hot","high","strong"],["overcast","hot","high","weak"],["rainy","mild","high","weak"],["rainy","cool","normal","weak"],["rainy","cool","normal","strong"],["overcast","cool","normal","strong"],["sunny","mild","high","weak"],["sunny","cool","normal","weak"],["rainy","mild","normal","weak"],["sunny","mild","normal","strong"],["overcast","mild","high","strong"],["overcast","hot","normal","weak"],["rainy","mild","high","strong"]]\ny_raw=["no","no","yes","yes","yes","no","yes","no","yes","yes","yes","yes","yes","no"]\nles=[LabelEncoder() for _ in range(4)]\nX=np.array([[les[i].fit_transform([r[i] for r in X_raw])[j] for i in range(4)] for j in range(len(X_raw))])\ny=LabelEncoder().fit_transform(y_raw)\nmodel=CategoricalNB(); model.fit(X,y)\nprint("Accuracy:",(model.predict(X)==y).mean())' },
    { title:'Data Preprocessing Techniques', aim:'Apply preprocessing: missing values, sampling, binning.', code:'import pandas as pd, numpy as np\nfrom sklearn.preprocessing import MinMaxScaler\nnp.random.seed(42)\ndf=pd.DataFrame({"age":[25,np.nan,35,45,np.nan,28,52,33,np.nan,41],"income":[30000,45000,np.nan,80000,25000,np.nan,95000,42000,38000,70000]})\nprint("Missing:\n",df.isnull().sum())\ndf["age"].fillna(df["age"].median(),inplace=True)\ndf["income"].fillna(df["income"].mean(),inplace=True)\ndf["age_group"]=pd.cut(df["age"],bins=[0,30,40,60],labels=["Young","Middle","Senior"])\ndf["income_norm"]=MinMaxScaler().fit_transform(df[["income"]])\nprint(df)' },
    { title:'Apriori Algorithm', aim:'Implement Apriori to discover frequent itemsets and association rules.', code:'# pip install mlxtend\nfrom mlxtend.frequent_patterns import apriori, association_rules\nfrom mlxtend.preprocessing import TransactionEncoder\nimport pandas as pd\ntransactions=[["bread","milk","butter"],["bread","diapers","beer","eggs"],["milk","diapers","beer","cola"],["bread","milk","diapers","beer"],["bread","milk","diapers","cola"],["milk","butter"],["bread","butter","eggs"],["bread","milk","diapers"]]\nte=TransactionEncoder()\ndf=pd.DataFrame(te.fit_transform(transactions),columns=te.columns_)\nfreq=apriori(df,min_support=0.375,use_colnames=True)\nprint("Frequent Itemsets:\n",freq)\nrules=association_rules(freq,metric="confidence",min_threshold=0.6)\nprint("\nRules:\n",rules[["antecedents","consequents","support","confidence","lift"]])' },
    { title:'K-Means and K-Medoids Clustering', aim:'Perform clustering using K-Means and K-Medoids.', code:'# pip install scikit-learn-extra\nfrom sklearn.cluster import KMeans\nfrom sklearn_extra.cluster import KMedoids\nfrom sklearn.datasets import make_blobs\nX,_=make_blobs(n_samples=150,centers=3,cluster_std=0.8,random_state=42)\nkm=KMeans(n_clusters=3,random_state=42,n_init=10)\nkm.fit(X)\nprint("K-Means Inertia:",km.inertia_)\nprint("Centers:\n",km.cluster_centers_)\nkmed=KMedoids(n_clusters=3,random_state=42)\nkmed.fit(X)\nprint("\nK-Medoids Centers:\n",kmed.cluster_centers_)' },
    { title:'Regression using WEKA', aim:'Evaluate regression techniques using WEKA.', code:'// WEKA Steps:\n// 1. Open WEKA Explorer -> Preprocess -> Open housing.arff\n// 2. Classify -> Choose -> functions -> LinearRegression\n// 3. Test: Cross-validation 10 folds -> Start\n// 4. Check: Correlation coefficient, MAE, RMSE\n// ARFF:\n// @relation housing\n// @attribute size NUMERIC\n// @attribute bedrooms NUMERIC\n// @attribute price NUMERIC\n// @data\n// 1500,3,250000\n// 2000,4,350000\n// 1200,2,180000' },
    { title:'Binning and Histogram Analysis', aim:'Implement binning and histogram analysis.', code:'import pandas as pd, numpy as np, matplotlib.pyplot as plt\nnp.random.seed(42)\nages=np.clip(np.random.normal(35,12,200).astype(int),18,70)\ndf=pd.DataFrame({"age":ages})\ndf["ew"]=pd.cut(df["age"],bins=5)\ndf["ef"]=pd.qcut(df["age"],q=5,duplicates="drop")\ndf["custom"]=pd.cut(df["age"],bins=[0,25,35,45,55,100],labels=["<25","25-35","35-45","45-55","55+"])\nprint("Equal-Width:\n",df["ew"].value_counts().sort_index())\nprint("\nCustom:\n",df["custom"].value_counts())\nplt.hist(ages,bins=10,color="steelblue",edgecolor="black")\nplt.title("Age Histogram"); plt.savefig("histogram.png")' },
    { title:'Classification Process on Given Data', aim:'Demonstrate full classification process on given data.', code:'from sklearn.datasets import load_iris\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.tree import DecisionTreeClassifier, export_text\nfrom sklearn.metrics import accuracy_score, classification_report\niris=load_iris()\nX_tr,X_te,y_tr,y_te=train_test_split(iris.data,iris.target,test_size=0.3,random_state=42,stratify=iris.target)\ndt=DecisionTreeClassifier(max_depth=3,random_state=42)\ndt.fit(X_tr,y_tr); pred=dt.predict(X_te)\nprint("Accuracy:",accuracy_score(y_te,pred))\nprint(classification_report(y_te,pred,target_names=iris.target_names))\nprint(export_text(dt,feature_names=iris.feature_names))' },
    { title:'Compare Classifiers using Confusion Matrix', aim:'Compare classification algorithm accuracies using confusion matrix.', code:'from sklearn.datasets import load_breast_cancer\nfrom sklearn.model_selection import train_test_split\nfrom sklearn.tree import DecisionTreeClassifier\nfrom sklearn.naive_bayes import GaussianNB\nfrom sklearn.svm import SVC\nfrom sklearn.neighbors import KNeighborsClassifier\nfrom sklearn.metrics import accuracy_score, confusion_matrix\ndata=load_breast_cancer()\nX_tr,X_te,y_tr,y_te=train_test_split(data.data,data.target,test_size=0.3,random_state=42)\nfor name,clf in [("DT",DecisionTreeClassifier(random_state=42)),("NB",GaussianNB()),("SVM",SVC(random_state=42)),("KNN",KNeighborsClassifier())]:\n    clf.fit(X_tr,y_tr); pred=clf.predict(X_te)\n    print(f"{name}: {accuracy_score(y_te,pred):.4f}\n",confusion_matrix(y_te,pred))' }
  ];

  var saved=loadSaved();
  $scope.practicals=practicalData.map(function(p,i){
    var id=i+1, s=saved[id]||{};
    return {id:id,title:p.title,aim:p.aim,code:p.code,completed:s.completed||false,notes:s.notes||'',showCode:false};
  });
  $scope.toggleComplete=function(p){p.completed=!p.completed;save();};
  $scope.toggleCode=function(p){p.showCode=!p.showCode;};
  $scope.saveNotes=function(){save();};
  $scope.completedCount=function(){return $scope.practicals.filter(function(p){return p.completed;}).length;};
}]);
